server:
  port: 9000
  tomcat:
    accesslog:
      directory: ${log-directory}
      enabled: true
      encoding: UTF-8
      max-days: 7

logging:
  level:
    org.springframework.web: DEBUG
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO
  file:
    name: ${log-directory}/vcloud.log
    max-history: 7
  pattern:
    rolling-file-name: vcloud-%d{yyyy-MM-dd}.%i.log

log-directory : test

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    initialization-mode: always

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: localhost
    password:
    isUsed: true

# cors 설정
cors:
  allowed-origins: 'http://localhost:9000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: ENC(3i/5RMkRtVFoOIbcVwhii1G4e4cB4Lg4eeoRW++hUdsfhJ076X0y6YN2s3JDbpsragCiyfo+Y73duXwhZ6QcRqfNYvk/IXYkO97jHXyEHN4=)
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:9000/oauth/redirect