spring:
  security:
    oauth2.client:
      registration:
        google:
          client-id: 'tempId'
          client-secret: 'tempSecret'
          scope:
            - email
            - profile
        facebook:
          client-id: 'tempId'
          client-secret: 'tempSecret'
          scope:
            - email
            - public_profile
        naver:
          client-id: 'tempId'
          client-secret: 'tempSecret'
          client-authentication-method: post
          authorization-grant-type: authorization_code
          redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          scope:
            - nickname
            - email
            - profile_image
          client-name: Naver
        kakao:
          client-id: ENC(qpFQmo0exEQTvgjO8pMKAHv4qo2bb4hDYnCOBr0GF30GJgBBtVUrL7lXQl15gvDC)
          client-secret: ENC(6VxMA0VTnAt977Q49o/hUq3esT7pEFbCape4uy3ZY4DQ3lv0+I4pgjmrWtlPKk7k)
          client-authentication-method: post
          authorization-grant-type: authorization_code
          redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          scope:
            - profile_nickname
            - profile_image
            - account_email
          client-name: Kakao

      # Provider 설정
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id